CREATE TABLE IF NOT EXISTS up_projector_projects
(
	ID INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_projector_issues
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	PROJECT_ID INT(11) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);